// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTMnOgbyLI2YuOjsT4ZuppYR5T_DoiEdw',
    appId: '1:6353235854:web:7a339fbf371f0c3a1d7edf',
    messagingSenderId: '6353235854',
    projectId: 'phisguard-a7118',
    authDomain: 'phisguard-a7118.firebaseapp.com',
    storageBucket: 'phisguard-a7118.firebasestorage.app',
    measurementId: 'G-D2NHZ82L5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVhCXE_3o8NA6jl8haKsOe4ojeTgaWVJk',
    appId: '1:6353235854:android:a19e3a44640efd7c1d7edf',
    messagingSenderId: '6353235854',
    projectId: 'phisguard-a7118',
    storageBucket: 'phisguard-a7118.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLK0w5TgBbwJa0iLTFnTKI6LeTucvP8k4',
    appId: '1:6353235854:ios:fc307e7a66703dfd1d7edf',
    messagingSenderId: '6353235854',
    projectId: 'phisguard-a7118',
    storageBucket: 'phisguard-a7118.firebasestorage.app',
    iosBundleId: 'com.phishguard.webapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLK0w5TgBbwJa0iLTFnTKI6LeTucvP8k4',
    appId: '1:6353235854:ios:fc307e7a66703dfd1d7edf',
    messagingSenderId: '6353235854',
    projectId: 'phisguard-a7118',
    storageBucket: 'phisguard-a7118.firebasestorage.app',
    iosBundleId: 'com.phishguard.webapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTMnOgbyLI2YuOjsT4ZuppYR5T_DoiEdw',
    appId: '1:6353235854:web:aa9ce6f1c166841a1d7edf',
    messagingSenderId: '6353235854',
    projectId: 'phisguard-a7118',
    authDomain: 'phisguard-a7118.firebaseapp.com',
    storageBucket: 'phisguard-a7118.firebasestorage.app',
    measurementId: 'G-5MJY87HTW3',
  );
}
